### ISSUE TITLE
Error executing vim.schedule lua callback: ... is already closing

### ISSUE THREAD

**Issue by ssoriche** [someone-stole-my-name/yaml-companion.nvim#10]
First off, thanks for creating this plugin, I do a lot of very different yaml file editing and getting the right schema is important.

I started receiving this error message from neovim this morning when opening a kubernetes Deployment manifest:

```
Error executing vim.schedule lua callback: .../yaml-companion.nvim/lua/yaml-companion/context/init.lua:65: handle 0x6000
00c54000 is already closing
stack traceback:
        [C]: in function 'close'
        .../yaml-companion.nvim/lua/yaml-companion/context/init.lua:65: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I am running neovim:

```
:version
NVIM v0.8.0-dev+e86901eb6
Build type: Release
LuaJIT 2.1.0-beta3
```

And my plugins are all up to date. Any ideas?

**Comment by someone-stole-my-name** [comment]
https://github.com/someone-stole-my-name/yaml-companion.nvim/commit/ab42ea608dfb8e82adb506cc90f85786efa37923 should fix it. My guess is that when closing one of the internal timers, a buffer was being closed or already closed. Do you have a way to reproduce it consistently?

**Comment by ssoriche** [comment]
I thought I was able to reproduce it consistently, but when I went back into the code that displayed the issue it didn't trigger. This was prior to updating to the new commit. I'll continue to try and see if it happens again prior to updating.

Thank you.
