### ISSUE TITLE
Adding custom matchers

### ISSUE THREAD

**Issue by pteroctopus** [someone-stole-my-name/yaml-companion.nvim#33]
Hi,

Thank you for the plugin. I will try it.

Could you give an example of how to add custom matchers by calling custom lua function.

If I see correctly there are two builtin matchers and for all else schema needs to be selected manualy via Telesope plugin.

BR,

**Comment by someone-stole-my-name** [comment]
The API is subject to change, as of right now all you have to do is call `require("yaml-companion").load_matcher("X")` where X is a module that has the `match` and `handles` functions, example [here](https://github.com/someone-stole-my-name/yaml-companion.nvim/blob/main/tests/dummy_matcher/lua/yaml-companion/_matchers/dummy.lua). You can check [here](https://github.com/someone-stole-my-name/yaml-companion.nvim/blob/main/lua/yaml-companion/_matchers/init.lua) the code that loads the matchers.
